## 1. Pandas

### 1.1 Introduction to Pandas

Pandas is a library that unifies the most common workflows that data analysts and data scientists previously relied on many different libraries for. Pandas has quickly became an important tool in a data professional's toolbelt and is the most popular library for working with tabular data in Python. Tabular data is any data that can be represented as rows and columns. The CSV files we've worked with in previous missions are all examples of tabular data.

To represent tabular data, pandas uses a custom data structure called a <span style="background-color: #F9EBEA; color:##C0392B">dataframe</span>. A dataframe is a highly efficient, <span style="background-color: #F9EBEA; color:##C0392B">2-dimensional data structure</span> that provides a suite of methods and attributes to quickly explore, analyze, and visualize data. The dataframe is similar to the NumPy 2D array but adds support for many features that help you work with tabular data.

One of the biggest advantages that pandas has over NumPy is the **ability to store mixed data types** in rows and columns. Many tabular datasets contain a range of data types and pandas dataframes handle mixed data types effortlessly while NumPy doesn't. Pandas dataframes **can also handle missing values gracefully** using a custom object, <span style="background-color: #F9EBEA; color:##C0392B">NaN</span>, to represent those values. A common complaint with NumPy is its lack of an object to represent missing values and people end up having to find and replace these values manually. In addition, pandas dataframes contain axis labels for both rows and columns and enable you to refer to elements in the dataframe more intuitively. Since many tabular datasets contain column titles, this means that dataframes preserve the metadata from the file around the data.

### 1.2 Introduction to the data

In this topic, you'll learn the basics of pandas while exploring a dataset from the [United States Department of Agriculture (USDA)](http://www.ars.usda.gov/Services/docs.htm?docid=8964). This dataset contains nutritional information on the most common foods Americans consume. Each column in the dataset shows a different attribute of the foods and each row describes a different food item.

Here are some of the columns in the dataset:

- <span style="background-color: #F9EBEA; color:##C0392B">NBD_No</span> - unique id of the food.
- <span style="background-color: #F9EBEA; color:##C0392B">Shrt_Desc</span> - name of the food.
- <span style="background-color: #F9EBEA; color:##C0392B">Water_(g)</span> - water content in grams.
- <span style="background-color: #F9EBEA; color:##C0392B">Energ_Kcal</span> - energy measured in kilo-calories.
- <span style="background-color: #F9EBEA; color:##C0392B">Protein_(g)</span> - protein measured in grams.
- <span style="background-color: #F9EBEA; color:##C0392B">Cholestrl_(mg)</span> - cholesterol in milligrams.

Here's a preview of the first few rows and columns in the dataset:

<img width="1000" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0dlZBSV9ORHpCMXc">

### 1.3 Read a CSV file

To use the Pandas library, we need to import it into the environment using the <span style="background-color: #F9EBEA; color:##C0392B">import</span> keyword:

>```python
import pandas
```

We can then refer to the module using <span style="background-color: #F9EBEA; color:##C0392B">pandas</span> and use dot notation to call its methods. To read a CSV file into a dataframe, we use the [pandas.read_csv()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) function and pass in the file name as a string:

>```python
import pandas as pd
food_info = pd.read_csv("food_info.csv")
```

### 1.4 Exploring the dataframe

Now that we've read the dataset into a dataframe, we can start using the dataframe methods to explore the data. To select the first 5 rows of a dataframe, use the dataframe method [head()](http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.head.html). When you call the <span style="background-color: #F9EBEA; color:##C0392B">head()</span> method, pandas will return a new dataframe containing just the first 5 rows:


>```python
first_rows = food_info.head()
```

If you peek at the [documentation](http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.head.html), you'll notice that you can pass in an integer (<span style="background-color: #F9EBEA; color:##C0392B">n</span>) into the <span style="background-color: #F9EBEA; color:##C0392B">head()</span> method to display the first <span style="background-color: #F9EBEA; color:##C0392B">n</span> rows instead of the first 5:

>```python
print(food_info.head(3))
```

Because this dataframe contains many columns and rows, pandas uses ellipsis (<span style="background-color: #F9EBEA; color:##C0392B">...</span>) to hide the columns and rows in the middle. Only the first few and the last few columns and rows are displayed to conserve space.

To access the full list of column names, use the <span style="background-color: #F9EBEA; color:##C0392B">columns</span> attribute:

>```python
column_names = food_info.columns
```

Lastly, you can use the <span style="background-color: #F9EBEA; color:##C0392B">shape</span> attribute to understand the dimensions of the dataframe. The <span style="background-color: #F9EBEA; color:##C0392B">shape</span> attribute returns a tuple of integers representing the number of rows followed by the number of columns:

>```python
# Returns the tuple (8618,36) and assigns to `dimensions`.
dimensions = food_info.shape
# The number of rows, 8618.
num_rows = dimensions[0]
# The number of columns, 36.
num_cols = dimensions[1]
```

### 1.5 Indexing

When you read in a file into a dataframe, pandas uses the values in the first row (also known as the header) for the column labels and the row number for the row labels. Collectively, the labels are referred to as the **index**. dataframes contain both a row index and a column index. Here's a diagram that displays some of the column and row labels for <span style="background-color: #F9EBEA; color:##C0392B">food_info</span>:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0SlNxZXdmM3dzUUU">

The labels allow us to refer to values in the dataframe, which we'll learn more about in the rest of this notebook.

### 1.6 Series

The **Series** object is a core data structure that pandas uses to represent rows and columns. A Series is a labelled collection of values similar to the NumPy vector. The main advantage of Series objects is the **ability to utilize non-integer labels**. NumPy arrays can only utilize integer labels for indexing.

Pandas utilizes this feature to provide more context when returning a row or a column from a dataframe. For example, when you select a row from a dataframe, instead of just returning the values in that row as a list, pandas returns a Series object that contains the column labels as well as the corresponding values:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0aUZ5c0FrQ0VNWFU">

The Series object representing the first row looks like:

<img width="300" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0Slg5TDdXNUt6V2M">

### 1.7 Selecting a row

While we use bracket notation to access elements in a NumPy array or a standard list, we need to use the pandas method [loc[]](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-label) to select rows in a dataframe. The <span style="background-color: #F9EBEA; color:##C0392B">loc[]</span> method allows you to select rows by row labels. Recall that when you read a file into a dataframe, pandas uses the row number (or position) as each row's label. Pandas uses zero-indexing, so the first row is at index 0, the second row at index 1, and so on.

If you're interested in accessing a single row, pass in the row label to the <span style="background-color: #F9EBEA; color:##C0392B">loc[]</span> method. Python will return an error if you don't pass in a valid row label:

>```python
# Series object representing the row at index 0.
food_info.loc[0]
# Series object representing the seventh row.
food_info.loc[6]
# Will throw an error: "KeyError: 'the label [8620] is not in the [index]'"
food_info.loc[8620]
```

When accessing an individual row, pandas returns a Series object containing the column names and that row's value for each column.

### 1.8 Data types

When you displayed individual rows, represented as Series objects, you may have noticed the text <span style="background-color: #F9EBEA; color:##C0392B">"dtype: object"</span> after the last value. <span style="background-color: #F9EBEA; color:##C0392B">"dtype: object"</span> refers to the data type, or **dtype**, of that Series. The object dtype is equivalent to the string type in Python. Pandas borrows from the NumPy type system and contains the following dtypes:

- <span style="background-color: #F9EBEA; color:##C0392B">"object"</span> - for representing string values.
- <span style="background-color: #F9EBEA; color:##C0392B">"int"</span> - for representing integer values.
- <span style="background-color: #F9EBEA; color:##C0392B">"float"</span> - for representing float values.
- <span style="background-color: #F9EBEA; color:##C0392B">"datatime"</span> - for representing time values.
- <span style="background-color: #F9EBEA; color:##C0392B">"bool"</span> - for representing Boolean values.

When reading a file into a dataframe, pandas analyzes the values and infers each column's types. To access the types - for each column, use the <span style="background-color: #F9EBEA; color:##C0392B">DataFrame.dtypes</span> attribute to return a Series containing each column name and its corresponding type. Read more about data types on the [Pandas documentation](http://pandas.pydata.org/pandas-docs/stable/basics.html#dtypes).

>```python
print(food_info.dtypes)
```

### 1.9 Selecting Multiple Rows

If you're interested in accessing multiple rows of the dataframe, you can pass in either a slice of row labels or a list of row labels and pandas will return a dataframe. Note that unlike slicing lists in Python, a slice of a dataframe using <span style="background-color: #F9EBEA; color:##C0392B">.loc[]</span> will include both the start and the end row:

>```python
# DataFrame containing the rows at index 3, 4, 5, and 6 returned.
food_info.loc[3:6]
# DataFrame containing the rows at index 2, 5, and 10 returned. Either of the following work.
# Method 1
two_five_ten = [2,5,10] 
food_info.loc[two_five_ten]
# Method 2
food_info.loc[[2,5,10]]
```

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**:

1. Select the last 5 rows of <span style="background-color: #F9EBEA; color:##C0392B">food_info</span> and assign to the variable <span style="background-color: #F9EBEA; color:##C0392B">last_rows</span>. #tips: use <span style="background-color: #F9EBEA; color:##C0392B">.loc[]</span> method.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
size = food_info.shape[0]
last_rows = food_info.loc[(size-5):size]
last_rows

### 1.10 Selecting Individual Columns

When accessing a column in a dataframe, pandas returns a Series object containing the row label and each row's value for that column. To access a single column, use bracket notation and pass in the column name as a string:

>```python
# Series object representing the "NDB_No" column.
ndb_col = food_info["NDB_No"]
# You can instead access a column by passing in a string variable.
col_name = "NDB_No"
ndb_col = food_info[col_name]
```

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**:

1. Assign the <span style="background-color: #F9EBEA; color:##C0392B">"FA_Sat_(g)"</span> column to the variable <span style="background-color: #F9EBEA; color:##C0392B">saturated_fat</span>.
2. Assign the <span style="background-color: #F9EBEA; color:##C0392B">"Cholestrl_(mg)"</span> column to the variable <span style="background-color: #F9EBEA; color:##C0392B">cholesterol</span>.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
saturated_fat =food_info["FA_Sat_(g)"]
cholesterol = food_info["Cholestrl_(mg)"]
saturated_fat

### 1.11 Selecting Multiple Columns By Name

To select multiple columns, pass in a list of strings representing the column names and pandas will return a dataframe containing only the values in those columns. The following code returns a dataframe containing the <span style="background-color: #F9EBEA; color:##C0392B">"Zinc_(mg)"</span> and <span style="background-color: #F9EBEA; color:##C0392B">"Copper_(mg)"</span> columns, in that order:

>```python
columns = ["Zinc_(mg)", "Copper_(mg)"]
zinc_copper = food_info[columns]
# Skipping the assignment.
zinc_copper = food_info[["Zinc_(mg)", "Copper_(mg)"]]
```

When selecting multiple columns, the order of the columns in the returned dataframe matches the order of the column names in the list of strings that you passed in. This allows you to easily explore specific columns that may not be positioned next to each other in the dataframe.


<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: select and display only the columns that use grams for measurement (that end with <span style="background-color: #F9EBEA; color:##C0392B">"(g)"</span>). To accomplish this:

1. Use the <span style="background-color: #F9EBEA; color:##C0392B">columns</span> attribute to return the column names in <span style="background-color: #F9EBEA; color:##C0392B">food_info</span> and convert to a list by calling the method <span style="background-color: #F9EBEA; color:##C0392B">tolist()</span>.
2. Create a *new list*, <span style="background-color: #F9EBEA; color:##C0392B">gram_columns</span>, containing only the column names that end in <span style="background-color: #F9EBEA; color:##C0392B">"(g)"</span>. The string method <span style="background-color: #F9EBEA; color:##C0392B">endswith()</span> returns <span style="background-color: #F9EBEA; color:##C0392B">True</span> if the string object calling the method ends with the string passed into the parentheses.
3. Pass <span style="background-color: #F9EBEA; color:##C0392B">gram_columns</span> into bracket notation to select just those columns and assign the resulting dataframe to <span style="background-color: #F9EBEA; color:##C0392B">gram_df</span>
4. Then use the dataframe method <span style="background-color: #F9EBEA; color:##C0392B">head()</span> to display the first 3 rows of <span style="background-color: #F9EBEA; color:##C0392B">gram_df</span>

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
column_names = food_info.columns.tolist()
for a in column_names:
    if(a.endswith('(g)')):
        gram_columns.append(a)
gram_df = pd.DataFrame(gram_columns)
gram_df.head(3)

## 2. Data manipulation with Pandas

### 2.1 Overview

In the previous sections, we learned how to explore a pandas <span style="background-color: #F9EBEA; color:##C0392B">DataFrame</span>. In this mission, we'll explore how to manipulate a DataFrame and make transformations to it. We'll continue to work with the same data set from the USDA on nutritional information. We'll build a basic nutritional index for people who want to eat high-protein, low-fat foods. The <span style="background-color: #F9EBEA; color:##C0392B">"Lipid\_Tot\_(g)"</span> column contains each food's total fat content, and the <span style="background-color: #F9EBEA; color:##C0392B">"Protein\_(g)"</span> (in grams) contains each food's total protein content (in grams). Let's use the following formula to score each food in our data set:

>$$ 
Score = 2 \times (Protein\_(g)) - 0.75 \times (Lipid\_Tot\_(g))
$$

While this formula is by no means scientific, it will act as a guide as we explore pandas further.

Just to remember, here's a preview of the data set:

<img width="1000" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0dlZBSV9ORHpCMXc">

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: to practice what we learned in the previous sections:

>1. Import the <span style="background-color: #F9EBEA; color:##C0392B">pandas</span>
2. Read <span style="background-color: #F9EBEA; color:##C0392B">food_info.csv</span> into a DataFrame object named <span style="background-color: #F9EBEA; color:##C0392B">food_info</span>.
3. Use the <span style="background-color: #F9EBEA; color:##C0392B">DataFrame.columns</span> attribute, followed by the <span style="background-color: #F9EBEA; color:##C0392B">Index.tolist()</span> method, to return a list containing only the column names.
4. Assign the resulting list to <span style="background-color: #F9EBEA; color:##C0392B">col_names</span>, and use the print() function to display the value.
5. Display the first three rows of <span style="background-color: #F9EBEA; color:##C0392B">food_info.csv</span>.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
col_names = food_info.columns.tolist()
food_info.head(3)

### 2.2 Transforming a column

We can use the arithmetic operators to transform a numerical column. The values in the <span style="background-color: #F9EBEA; color:##C0392B">"Iron\_(mg)"</span> column, for example, are currently in milligrams. We can divide each value by <span style="background-color: #F9EBEA; color:##C0392B">1000</span> to convert the values to grams. The following code will divide each value in the <span style="background-color: #F9EBEA; color:##C0392B">"Iron\_(mg)"</span> column by <span style="background-color: #F9EBEA; color:##C0392B">1000</span>, and return a new Series object with those values:

>```python
div_1000 = food_info["Iron_(mg)"] / 1000
```

pandas allows us to use any of the arithmetic operators to scale the values in a numerical column:


>```python
# Adds 100 to each value in the column and returns a Series object.
add_100 = food_info["Iron_(mg)"] + 100
# Subtracts 100 from each value in the column and returns a Series object.
sub_100 = food_info["Iron_(mg)"] - 100
# Multiplies each value in the column by 2 and returns a Series object.
mult_2 = food_info["Iron_(mg)"]*2
```

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Divide the <span style="background-color: #F9EBEA; color:##C0392B">"Sodium_(mg)"</span> column by 1000 to convert the values to grams, and assign the result to <span style="background-color: #F9EBEA; color:##C0392B">sodium_grams</span>.
2. Multiply the <span style="background-color: #F9EBEA; color:##C0392B">"Sugar\_Tot\_(g)"</span> column by 1000 to convert to milligrams, and assign the result to <span style="background-color: #F9EBEA; color:##C0392B">sugar_milligrams</span>.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
sodium_grams = food_info["Sodium_(mg)"] / 1000
sugar_milligrams = food_info["Sugar_Tot_(g)"] * 1000

sugar_milligrams

### 2.3 Performing math with multiple columns

In addition to transforming columns by numerical values, we can transform columns by other columns. When we use an arithmetic operator between two columns (Series objects), pandas will perform that computation in a pair-wise fashion, and return a new Series object. It applies the arithmetic operator to the first value in both columns, the second value in both columns, and so on.

In the following code, we multiply the <span style="background-color: #F9EBEA; color:##C0392B">"Water_(g)"</span> column by the <span style="background-color: #F9EBEA; color:##C0392B">"Energ_Kcal"</span> column, and assign the resulting Series to <span style="background-color: #F9EBEA; color:##C0392B">water_energy</span>:

>```python
water_energy = food_info["Water_(g)"] * food_info["Energ_Kcal"]
```

The following diagram may help you understand pair-wise computation a bit better:

<img width="500" alt="creating a repo" src="https://drive.google.com/uc?export=view&id=0BxhVm1REqwr0cWxQZkI0c2IxemM">


<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Assign the number of grams of protein per gram of water (<span style="background-color: #F9EBEA; color:##C0392B">"Protein\_(g)"</span> column divided by <span style="background-color: #F9EBEA; color:##C0392B">"Water\_(g)"</span> column) to <span style="background-color: #F9EBEA; color:##C0392B">grams_of_protein_per_gram_of_water</span>.
2. Assign the total amount of calcium and iron (<span style="background-color: #F9EBEA; color:##C0392B">"Calcium\_(mg)"</span> column plus <span style="background-color: #F9EBEA; color:##C0392B">"Iron\_(mg)"</span> column) to <span style="background-color: #F9EBEA; color:##C0392B">milligrams\_of\_calcium\_and\_iron</span>.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
grams_of_protein_per_gram_of_water = food_info["Protein_(g)"] / food_info["Water_(g)"]
milligrams_of_calcium_and_iron = food_info["Calcium_(mg)"] + food_info[ "Iron_(mg)"]

grams_of_protein_per_gram_of_water
milligrams_of_calcium_and_iron

### 2.4 Create a nutritional index

Now that we've learned how to transform columns with a numerical value and how to combine columns, we can use the following formula to create a nutritional index:

> $$ Score=2×(Protein\_(g))−0.75×(Lipid\_Tot\_(g)) $$


<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Multiply the <span style="background-color: #F9EBEA; color:##C0392B">"Protein\_(g)" </span> column by two, and assign the resulting Series to <span style="background-color: #F9EBEA; color:##C0392B">weighted_protein</span>.
2. Multiply the <span style="background-color: #F9EBEA; color:##C0392B">"Lipid\_Tot\_(g)"</span> column by -0.75, and assign the resulting Series to <span style="background-color: #F9EBEA; color:##C0392B">weighted_fat</span>.
3. Add both Series objects together and assign the result to <span style="background-color: #F9EBEA; color:##C0392B">initial_rating</span>.

In [ ]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
weighted_protein = food_info["Protein_(g)"] / 2
weighted_fat = food_info["Lipid_Tot_(g)"] * (-0.75)
initial_rating = weighted_protein + weighted_fat
initial_rating

### 2.5 Normalize columns in a dataset

The columns in the data set use different units (kilo-calories, milligrams, etc.). As a result, the range of values varies greatly between columns. For example, the <span style="background-color: #F9EBEA; color:##C0392B">"Vit\_A\_IU"</span> column ranges from 0 to 100000, while the <span style="background-color: #F9EBEA; color:##C0392B">"Fiber\_TD\_(g)"</span> column ranges from 0 to 79. For certain calculations, columns like <span style="background-color: #F9EBEA; color:##C0392B">"Vit_A_IU"</span> can have a greater effect on the result, due to the scale of the values.

While there are many ways to normalize data, one of the simplest ways is to divide all of the values in a column by that column's maximum value. This way, all of the columns will range from 0 to 1. To calculate the maximum value of a column, we use the <span style="background-color: #F9EBEA; color:##C0392B">Series.max()</span> method. In the following code, we use the <span style="background-color: #F9EBEA; color:##C0392B">Series.max()</span> method to calculate the largest value in the <span style="background-color: #F9EBEA; color:##C0392B">"Energ_Kcal"</span> column, and assign it to <span style="background-color: #F9EBEA; color:##C0392B">max_calories</span>:

>```python
# The largest value in the "Energ_Kcal" column.
max_calories = food_info["Energ_Kcal"].max()
```

We can then use the division operator (<span style="background-color: #F9EBEA; color:##C0392B">/</span>) to divide the values in the <span style="background-color: #F9EBEA; color:##C0392B">"Energ_Kcal"</span> column by the maximum value, <span style="background-color: #F9EBEA; color:##C0392B">max_calories</span>:

>```python
# Divide the values in "Energ_Kcal" by the largest value.
normalized_calories = food_info["Energ_Kcal"] / max_calories
```

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Normalize the values in the <span style="background-color: #F9EBEA; color:##C0392B">"Protein_(g)"</span> column, and assign the result to <span style="background-color: #F9EBEA; color:##C0392B">normalized_protein</span>.
2. Normalize the values in the <span style="background-color: #F9EBEA; color:##C0392B">"Lipid\_Tot\_(g)"</span> column, and assign the result to <span style="background-color: #F9EBEA; color:##C0392B">normalized_fat</span>.

In [54]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
max_protein = food_info["Protein_(g)"].max()
max_lipid = food_info["Lipid_Tot_(g)"].max()

normalized_protein = food_info["Protein_(g)"] / max_protein
normalized_fat = food_info["Lipid_Tot_(g)"] / max_lipid

0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
5       0.2768
6       0.2426
7       0.2920
8       0.3382
9       0.3060
10      0.3211
11      0.0430
12      0.0385
13      0.0029
14      0.0227
15      0.0102
16      0.3424
17      0.2780
18      0.2128
19      0.3114
20      0.2951
21      0.2744
22      0.3234
23      0.2725
24      0.3028
25      0.2235
26      0.2464
27      0.1592
28      0.1972
29      0.3004
         ...
8588    0.0090
8589    0.0020
8590    0.0020
8591    0.1520
8592    0.0546
8593    0.0950
8594    0.0020
8595    0.0510
8596    0.0750
8597    0.1710
8598    0.7780
8599    1.0000
8600    0.0000
8601    0.1950
8602    0.0210
8603    0.0240
8604    0.0000
8605    0.0003
8606    0.0020
8607    0.0001
8608    0.0300
8609    0.0010
8610    0.0090
8611    0.0185
8612    0.0030
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

### 2.6 Creating a new column

So far, we've assigned the Series object that results from a column transform to a variable. However, we can add it to the DataFrame as a new column instead.

We add bracket notation to specify the name we want for that column, then use the assignment operator (<span style="background-color: #F9EBEA; color:##C0392B">=</span>) to specify the Series object containing the values we want to assign to that column:

>```python
iron_grams = food_info["Iron_(mg)"] / 1000  
food_info["Iron_(g)"] = iron_grams
```

The DataFrame <span style="background-color: #F9EBEA; color:##C0392B">food\_info</span> now includes the <span style="background-color: #F9EBEA; color:##C0392B">"Iron\_(g)"</span> column, which contains the values from <span style="background-color: #F9EBEA; color:##C0392B">iron\_grams</span>.


<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Assign the normalized <span style="background-color: #F9EBEA; color:##C0392B">"Protein\_(g)"</span> column to a new column named <span style="background-color: #F9EBEA; color:##C0392B">"Normalized\_Protein"</span> in <span style="background-color: #F9EBEA; color:##C0392B">food\_info</span>.
2. Assign the normalized <span style="background-color: #F9EBEA; color:##C0392B">"Lipid\_Tot\_(g)"</span> column to a new column named <span style="background-color: #F9EBEA; color:##C0392B">"Normalized\_Fat"</span> in <span style="background-color: #F9EBEA; color:##C0392B">food_info</span>.
3. Use the <span style="background-color: #F9EBEA; color:##C0392B">Normalized\_Protein</span> and <span style="background-color: #F9EBEA; color:##C0392B">Normalized\_Fat</span> columns with the formula above (section 2.4) to create the <span style="background-color: #F9EBEA; color:##C0392B">Norm\_Nutr\_Index</span> column.

In [58]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
max_protein = food_info["Protein_(g)"].max()
max_lipid = food_info["Lipid_Tot_(g)"].max()

normalized_protein = food_info["Protein_(g)"] / max_protein
normalized_fat = food_info["Lipid_Tot_(g)"] / max_lipid

food_info[ "Normalized_Protein"] = normalized_protein
food_info[ "Normalized_Fat"] = normalized_fat

food_info["Norm_Nutr_Index"] = (2 * food_info[ "Normalized_Protein"]) - (0.75 * food_info[ "Normalized_Fat"])
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134,0.2968,0.303668

### 2.7 Sorting a dataframe by a column

The DataFrame currently appears in numerical order according to the <span style="background-color: #F9EBEA; color:##C0392B">NDB\_No</span> column. <span style="background-color: #F9EBEA; color:##C0392B">NDB\_No</span> is a unique USDA identifier that isn't really useful for our needs. To explore which foods rank the highest in the <span style="background-color: #F9EBEA; color:##C0392B">Norm\_Nutr\_Index</span> column, we need to sort the DataFrame by that column. DataFrame objects have a <span style="background-color: #F9EBEA; color:##C0392B">sort_values()</span> method that we can use to sort the entire DataFrame.

To sort the DataFrame on the <span style="background-color: #F9EBEA; color:##C0392B">Sodium\_(mg)</span> column, pass in the column name to the <span style="background-color: #F9EBEA; color:##C0392B">DataFrame.sort_values()</span> method, and assign the resulting DataFrame to a new variable:

>```python
food_info.sort_values("Sodium_(mg)")
```

By default, pandas will sort the data by the column we specify in ascending order and return a new DataFrame, rather than modifying <span style="background-color: #F9EBEA; color:##C0392B">food_info</span> itself. To customize the method's behavior, use the parameters listed in the [documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html):

>```python
# Sorts the DataFrame in-place, rather than returning a new DataFrame.
food_info.sort_values("Sodium_(mg)", inplace=True)
# Sorts by descending order, rather than ascending.
food_info.sort_values("Sodium_(mg)", inplace=True, ascending=False)
```

<br>
<div class="alert alert-info">
<b>Exercise Start.</b>
</div>

**Description**: 

>1. Sort the <span style="background-color: #F9EBEA; color:##C0392B">food_info</span> DataFrame in-place on the <span style="background-color: #F9EBEA; color:##C0392B">Norm\_Nutr\_Index</span> column in descending order.

In [60]:
#DONE
import pandas as pd
food_info = pd.read_csv("food_info.csv")
max_protein = food_info["Protein_(g)"].max()
max_lipid = food_info["Lipid_Tot_(g)"].max()

normalized_protein = food_info["Protein_(g)"] / max_protein
normalized_fat = food_info["Lipid_Tot_(g)"] / max_lipid

food_info[ "Normalized_Protein"] = normalized_protein
food_info[ "Normalized_Fat"] = normalized_fat

food_info["Norm_Nutr_Index"] = (2 * food_info[ "Normalized_Protein"]) - (0.75 * food_info[ "Normalized_Fat"])
food_info.sort_values("Norm_Nutr_Index", inplace=True, ascending=False)

food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.0,0.0,0.066,0.101,0.258,0.0,1.000000,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.0,0.0,0.070,0.060,0.010,0.0,0.969203,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.0,0.0,0.147,0.173,0.070,20.0,0.958220,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.932971,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,NaN,NaN,0.600,1.330,0.370,NaN,0.935236,0.0230,1.853221